name: 'Deploys for Windows'
description: 'Deploys the Windows build'
runs:
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: PrintToolWindows
          path: ${{github.workspace}}/artifacts
        shell: pwsh
      - run: ${{github.workspace}}/artifacts/PrintTool.exe "Hello" "world" "windows"
        name: Run print tool
        shell: pwsh
