name: Build Printtool
on: 
  schedule:
    - cron:  '0 0 * * 3'
  push:
    paths-ignore:
      - .azure-pipelines/**
      - .devcontainer/**
      - .vscode/**
      - .github/workflows/refactored.yml
  workflow_dispatch:
  pull_request:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  #Specifies whether .NET welcome and telemetry messages are displayed on the first run.
  DOTNET_NOLOGO: true
  #Specifies whether to generate an ASP.NET Core certificate.
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  NUGET_PACKAGES: '${{github.workspace}}/.nuget/packages'
  BUILD_CONFIG: 'Release'
  BUILD_ARCHITECTURE: 'x64'

defaults:
  run:
    shell: pwsh
    
jobs:
  main_matrix:
    strategy: 
      matrix:
        include: 
          - os: ubuntu-latest
            name: "Linux"
          - os: windows-latest
            name: "Windows"
    runs-on: ${{ matrix.os }}
    steps: 
      - uses: actions/checkout@v4   
        name: Checkout
      - id: build
        uses: dmbuzink/PrintToolWorkflows/.github/actions/build@master
        name: "Build for ${{ matrix.name }}"
        with:
          BUILD_CONFIG: ${{env.BUILD_CONFIG}}
          BUILD_ARCHITECTURE: ${{env.BUILD_ARCHITECTURE}}
          OS_VERSION: ${{ matrix.os }}
          OS_NAME: ${{ matrix.name }}
      - id: deploy
        uses: dmbuzink/PrintToolWorkflows/.github/actions/deploy@master
        if: ${{ github.event_name != 'pull_request' }}
        name: "Deploy ${{ matrix.name }}"
        with:
          OS_VERSION: ${{ matrix.os }}
          OS_NAME: ${{ matrix.name }}
        
        

    # deploy_windows:
    #   name: Deploy for Windows
    #   if: ${{ github.event_name != 'pull_request' }}
    #   runs-on: windows-latest
    #   needs: [build_windows]
    #   steps:
    #     - uses: actions/checkout@v4   
    #       name: Checkout
    #     - id: deploy-windows
    #       uses: dmbuzink/PrintToolWorkflows/.github/actions/deploy-windows@master
    #       name: 'Deploy Windows'
    # deploy_linux:
    #   name: Deploy for Linux
    #   if: ${{ vars.SHOULD_SKIP_LINUX == 'false' && github.event_name != 'pull_request' }}
    #   runs-on: ubuntu-latest
    #   needs: [build_linux]
    #   environment: printool_linux
    #   steps:
    #     - uses: actions/checkout@v4   
    #       name: Checkout
    #     - id: deploy-linux
    #       uses: dmbuzink/PrintToolWorkflows/.github/actions/deploy-linux@master
    #       name: 'Deploy linux'
